### ISSUE TITLE
IIS3DWB vibration sensor support

### ISSUE THREAD

**Issue by Pankaj-Patil-97** [STMicroelectronics/STMems_Linux_IIO_drivers#17]
Hello, 

I'm using IIS3DWB with ESP32 and planning on using Jetson xavier nx as the next hardware.
Would like to develop and publish the device driver for IIS3DWB.

Would **IIS3DHHC** be a good reference for developing the driver? 
https://github.com/STMicroelectronics/STMems_Linux_IIO_drivers/blob/linux-4.4.y-gh/drivers/iio/accel/st_lis3dhh.c

Thank you

**Comment by mariotesi** [comment]
Hi,

It could be interesting to develop a linux driver for the IIS3DWB. Please note however that the IIS3DWB ODR is fixed to 26.6kHz, so it is much faster than IIS3DHHC.

If you need help from ST, please open a case from the online support page ( [LINK ](https://community.st.com/s/onlinesupport)), detailing the business purpose and the target application, so that it can be officailly tracked.

Regards
